import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>


      <body>
       <nav className="bg-black text-white flex justify-between text-xl content-baseline"> <h1 className="m-2">Navbar</h1>  <button className="rounded p-1 bg-white text-black m-2">Sign in </button></nav> 
      <main>  {children}</main>
        
        </body>
    </html>
  );
}
